window.products = [
    // Fridge
    { name: "Dunnes Stores Irish Whole Milk 1 Litre", category: "Fridge", price: "€1.21" },
    { name: "Łaciate 2,0% UHT Milk 1.5 Litre", category: "Fridge", price: "€2.45" },
    { name: "Dunnes Stores 12 Irish Free Range Eggs Medium", category: "Fridge", price: "€4.09" },
    { name: "Dunnes Stores 6 Irish Free Range Eggs Medium", category: "Fridge", price: "€2.09" },
    { name: "Dunnes Stores Organic Greek Style Natural Yogurt 500g", category: "Fridge", price: "€1.89" },
    { name: "Dunnes Stores Fresh Italian Ricotta 250g", category: "Fridge", price: "€1.29" },
    { name: "Mlekpol Semi-Fat Curd Cheese 275g", category: "Fridge", price: "€2.30" },
    { name: "Dunnes Stores My Family Favourites Irish Creamery Butter 454g", category: "Fridge", price: "€3.99" },
    { name: "Dunnes Stores My Family Favourites Irish Mild White Cheddar 500g", category: "Fridge", price: "€3.00" },
    { name: "Coburger Brie 200g", category: "Fridge", price: "€1.54" },
    { name: "Dunnes Stores Fresh Cream 250ml", category: "Fridge", price: "€1.59" },
    { name: "Dunnes Stores My Family Favourites Mozzarella 200g", category: "Fridge", price: "€0.75" },
    { name: "Dunnes Stores Mild & Firm Halloumi 250g", category: "Fridge", price: "€2.75", icon: "🧀" },
    { name: "Dunnes Stores Organic Irish Beef Round Steak Mince 355g", category: "Fridge", price: "€5.19", icon: "🥩" },
    { name: "Dunnes Stores Spanish Style Potato & Onion Tortilla 500g", category: "Fridge", price: "€2.00", icon: "🍳" },

    // Pantry
    { name: "Dunnes Stores Organic Spelt Sourdough 720g", category: "Pantry", price: "€3.42" },
    { name: "Dunnes Stores Organic Ancient Grains 4 Seed Sourdough 800g", category: "Pantry", price: "€3.67" },
    { name: "Dunnes Stores Organic Rye Sourdough 690g", category: "Pantry", price: "€3.50" },
    { name: "Dunnes Stores House Organic Seeded Sourdough 785g", category: "Pantry", price: "€3.40" },
    { name: "Dunnes Stores Italian Chopped Tomatoes in a Rich Tomato Juice 400g", category: "Pantry", price: "€1.00" },
    { name: "It'za 8 Plain Wraps 320g", category: "Pantry", price: "€1.00", icom: "🌮" },
    { name: "Dunnes Stores Wholefoods Chickpeas in Water 400g", category: "Pantry", price: "€0.44" },
    { name: "Dunnes Stores Wholefoods Cannellini Beans in Water 400g", category: "Pantry", price: "€0.85" },
    { name: "Folláin Nothing But Fruit Blackcurrant 340g", category: "Pantry", price: "€2.50" },
    { name: "Dunnes Stores Tomato Purée 140g", category: "Pantry", price: "€1.20" },
    { name: "Dunnes Stores Unsalted Rice Cakes 130g", category: "Pantry", price: "€0.69" },
    { name: "TREK White Choc & Raspberry Protein Flapjacks 3 x 50g", category: "Pantry", price: "€3.50" },
    { name: "TREK Biscoff Protein Flapjack 3 x 50g", category: "Pantry", price: "€3.50" },
    { name: "Kind Protein Dark Chocolate Nut Bars 3 x 42g (126g)", category: "Pantry", price: "€2.14" },
    { name: "Kind Protein Crunchy Peanut Butter 3 x 42g (126g)", category: "Pantry", price: "€2.14" },
    { name: "Dunnes Stores Wholefoods Bulgur Wheat 500g", category: "Pantry", price: "€1.49" },
    { name: "Dunnes Stores Wholefoods Butter Beans in Water 400g", category: "Pantry", price: "€1.09" },
    { name: "Dunnes Stores Wholefoods Red Kidney Beans in Water 400g", category: "Pantry", price: "€0.90" },
    { name: "Dunnes Stores Wholefoods Red Split Lentils 500g", category: "Pantry", price: "€0.95" },
    { name: "Epicure Organic Bijoux Verts Lentils in Water 400g", category: "Pantry", price: "€1.25" },
    { name: "Epicure Organic Black Beans in Water 400g", category: "Pantry", price: "€1.25" },
    { name: "Gem Bread Soda 500g", category: "Pantry", price: "€1.50" },
    { name: "Dunnes Stores Sparkling Irish Spring Water 6 x 2 Litre", category: "Pantry", price: "€3.10", icon: "💧" },
    { name: "Dunnes Stores Italian Tomato Passata 500g", category: "Pantry", price: "€0.62" },
    { name: "Dunnes Stores Spanish Extra Virgin Olive Oil 500ml", category: "Pantry", price: "€4.09" },
    { name: "Dunnes Stores Baking at Home Cocoa Powder 250g", category: "Pantry", price: "€3.49" },
    { name: "Dunnes Stores My Family Favourites Basmati Rice 1kg", category: "Pantry", price: "€1.59" },
    { name: "Dunnes Stores Organic Porridge Oats Wholegrain 1kg", category: "Pantry", price: "€1.39" },
    { name: "Dunnes Stores Organic Coconut Milk 400ml", category: "Pantry", price: "€1.39", icon: "🥥" },
    { name: "Dunnes Stores My Family Favourites Plain Flour 2kg", category: "Pantry", price: "€1.59" },
    { name: "Frontier Foods Tahini 270g", category: "Pantry", price: "€3.00" },

    // Treats
    { name: "Reese's Milk Chocolate and Peanut Butter Cups, Multipack (5 Pack), 77g", category: "Treats", price: "€1.62" },
    { name: "McVitie's Signature Chocolate Cream Swirls 142g", category: "Treats", price: "€2.00" },
    { name: "Dunnes Stores Dark Chocolate Digestive Biscuits 300g", category: "Treats", price: "€1.00" },
    { name: "Catch Funsize Bars 192g", category: "Treats", price: "€1.99" },

    // Fresh Produce
    { name: "Dunnes Stores Organic Carrots 1kg", category: "Fresh Produce", price: "€1.69" },
    { name: "Dunnes Stores Handpicked Irish Baby Strawberries 125g", category: "Fresh Produce", price: "€1.29", icon: "🍓" },
    { name: "Dunnes Stores 6 Fresh Bananas", category: "Fresh Produce", price: "€1.33" },
    { name: "Dunnes Stores Peppery Wild Rocket Leaves 100g", category: "Fresh Produce", price: "€1.15" },
    { name: "Dunnes Stores Organic Cucumber", category: "Fresh Produce", price: "€1.39" },
    { name: "Dunnes Stores Grapefruit Loose 1'S", category: "Fresh Produce", price: "€0.49" },
    { name: "Dunnes Stores Fresh Avocados 700g", category: "Fresh Produce", price: "€3.19" },
    { name: "Dunnes Stores Supersweet Corn on the Cob 600g", category: "Fresh Produce", price: "€1.00" },
    { name: "Donnelly Fresh Citrus Easy Peelers 1kg", category: "Fresh Produce", price: "€2.65" },
    { name: "Dunnes Stores Fresh Root Ginger x 175g", category: "Fresh Produce", price: "€0.99", icon: "" },
    { name: "Dunnes Stores Italian Style Salad Mix 170g", category: "Fresh Produce", price: "€1.00" },
    { name: "Dunnes Stores Green Kiwi 4pk", category: "Fresh Produce", price: "€2.49" },
    { name: "Dunnes Stores Fresh Sweet Potatoes 750g", category: "Fresh Produce", price: "€1.09" },
    { name: "Dunnes Stores Fresh Irish Parsnips", category: "Fresh Produce", price: "€0.69", icon: "🥕" },
    { name: "Dunnes Stores Fresh Broccoli", category: "Fresh Produce", price: "€1.65" },
    { name: "Dunnes Stores Cauliflower", category: "Fresh Produce", price: "€1.99" },
    { name: "Dunnes Stores Loose Aubergine", category: "Fresh Produce", price: "€0.89", icon: "🍆" },
    { name: "Dunnes Stores Loose Courgette", category: "Fresh Produce", price: "€0.69" },
    { name: "Dunnes Stores Microwave Baby Potatoes 400g", category: "Fresh Produce", price: "€0.49" },
    { name: "Dunnes Stores Rustic Irish Garlic", category: "Fresh Produce", price: "€0.49" },
    { name: "Dunnes Stores Red Pepper", category: "Fresh Produce", price: "€0.99" },
    { name: "Dunnes Stores Organic Irish Potatoes 2kg", category: "Fresh Produce", price: "€2.99" },
    { name: "Dunnes Stores Organic Celery", category: "Fresh Produce", price: "€1.59", icon: "🥬" },
    { name: "Dunnes Stores My Family Favourites Red Onions", category: "Fresh Produce", price: "€0.99" },
    { name: "Dunnes Stores My Family Favourites Onions 1kg", category: "Fresh Produce", price: "€1.19" },
    { name: "Dunnes Stores Organic Vine Tomatoes 400g", category: "Fresh Produce", price: "€2.49", icon: "🍅" },

    // Meat & Veggie Alt
    { name: "Quorn Vegetarian Pieces 500g", category: "Meat & Alt", price: "€3.59" },
    { name: "Sons of Butchers Cheatballs 200g", category: "Meat & Alt", price: "€2.49" },
    { name: "Sons of Butchers Trick'n Strips 160g", category: "Meat & Alt", price: "€2.49" },
    { name: "The Tofoo Co. Smoked Organic Tofu 225g", category: "Meat & Alt", price: "€3.20" },
    { name: "Dunnes Stores Wafer Thin Chilli Glazed Irish Ham 10 Slices 130g", category: "Meat & Alt", price: "€1.75" },
    { name: "Dunnes Stores Wafer Thin Smoked Bourbon Glazed Irish Ham 10 Slices 130g", category: "Meat & Alt", price: "€1.75" },
    { name: "Quorn Vegan Chicken Free Slices 100g", category: "Meat & Alt", price: "€2.00" },
    { name: "Quorn 12 Veggie Ham Slices 170g", category: "Meat & Alt", price: "€3.39" },
    { name: "Quorn 12 Veggie Chicken Slices 170g", category: "Meat & Alt", price: "€3.39" },

    // Freezer
    { name: "Dunnes Stores Freshly Frozen Petits Pois & Sweetcorn 750g", category: "Freezer", price: "€1.09" },
    { name: "Dunnes Stores Freshly Frozen Very Fine Green Beans 500g", category: "Freezer", price: "€1.00" },
    { name: "Ardo Cultivated Blueberries 450g", category: "Freezer", price: "€2.50" },
    { name: "Ardo Raspberries 300g", category: "Freezer", price: "€2.50" },

    // Household & Pets
    { name: "Dunnes Stores Multi Purpose Kitchen Towel 3 Ply 4 Rolls", category: "Household", price: "€2.20" },
    { name: "Comfort Fabric Conditioner Pure 31 washes (930 ml)", category: "Household", price: "€2.50" },
    { name: "Dunnes Stores Toilet Tissue 12 Rolls", category: "Household", price: "€4.00" },
    { name: "Shannon Baking Parchment 12m", category: "Household", price: "€2.20" },
    { name: "Crystale Platinum Dishwasher Tablets Lemon Fresh 26x18g (468g)", category: "Household", price: "€2.50" },
    { name: "Dunnes Stores Rinse Aid for Dishwasher 1 Litre", category: "Household", price: "€2.75" },
    { name: "Dishmatic 6 General Purpose Refills", category: "Household", price: "€4.20" },
    { name: "Dunnes Stores Classic Cat Food Chunks in Jelly Mixed Selection - Adult- 6 x 400g (2.4kg)", category: "Household", price: "€4.89" },
    { name: "Dunnes Stores My Family Favourites Cat Food Meaty Selection in Gravy 6x400g", category: "Household", price: "€3.69" },
    { name: "Kleenex Supporting Mind - Single Cube Tissue Box", category: "Household", price: "€2.00" },

    // Baby
    { name: "Dunnes Stores 36 Baby-Dry Easy on Easy off Pants 5 12-17kg", category: "Baby", price: "€4.19" },
    { name: "Glenilen Farm Kids Yoghurt Natural 90g", category: "Baby", price: "€0.89" },
    { name: "Dunnes Stores Cleansing Cotton Pads", category: "Baby", price: "€2.00" },
    { name: "Sudocrem Antiseptic Healing Cream 250g", category: "Baby", price: "€8.00" },
    { name: "Beeline Kids Vitamin D3 Pump 28ml", category: "Baby", price: "€6.75" },
];
