window.products = [
    {
        name: "Fridge",
        items: [
            { name: "Dunnes Stores Irish Whole Milk 1 Litre", url: "https://www.dunnesstoresgrocery.com/product/dunnes-stores-irish-whole-milk-1-litre-id-100806906" },
            { name: "Łaciate 2,0% UHT Milk 1.5 Litre", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/aciate-20-uht-milk-15-litre-id-100193079" },
            { name: "Dunnes Stores Organic Greek Style Natural Yogurt 500g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-organic-greek-style-natural-yogurt-500g-id-100292839" },
            { name: "Dunnes Stores Fresh Italian Ricotta 250g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-fresh-italian-ricotta-250g-id-100856363" },
            { name: "Mlekpol Semi-Fat Curd Cheese 275g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/mlekpol-semifat-curd-cheese-275g-id-100193192" },
            { name: "Dunnes Stores My Family Favourites Irish Creamery Butter 454g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-my-family-favourites-irish-creamery-butter-454g-id-100806879" },
            { name: "Dunnes Stores My Family Favourites Irish Mild White Cheddar 500g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-my-family-favourites-irish-mild-white-cheddar-500g-id-100820352" },
            { name: "Coburger Brie 200g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/coburger-brie-200g-id-100826188" },
            { name: "Dunnes Stores Fresh Cream 250ml" },
            { name: "Dunnes Stores My Family Favourites Mozzarella 200g" },
            { name: "Dunnes Stores Mild & Firm Halloumi 250g", icon: "🧀" },
            { name: "Dunnes Stores Organic Irish Beef Round Steak Mince 355g", icon: "🥩" },
            { name: "Dunnes Stores Spanish Style Potato & Onion Tortilla 500g", icon: "🍳", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-spanish-style-potato-&-onion-tortilla-500g-id-100301804" },
        ],
    },
    {
        name: "Pantry",
        items: [
            { name: "Dunnes Stores 12 Irish Free Range Eggs Medium", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-12-irish-free-range-eggs-medium-id-100285942" },
            { name: "Dunnes Stores Organic Spelt Sourdough 720g", icon: "🍞", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-organic-100-spelt-sourdough-740g-id-100269826" },
            { name: "Dunnes Stores Organic Ancient Grains 4 Seed Sourdough 800g", icon: "🍞" },
            { name: "Dunnes Stores Organic Rye Sourdough 690g", icon: "🍞" },
            { name: "Dunnes Stores House Organic Seeded Sourdough 785g", icon: "🍞" },
            { name: "Dunnes Stores Italian Chopped Tomatoes in a Rich Tomato Juice 400g" },
            { name: "It'za 8 Plain Wraps 320g", icon: "🌮" },
            { name: "Dunnes Stores Wholefoods Chickpeas in Water 400g" },
            { name: "Dunnes Stores Wholefoods Cannellini Beans in Water 400g" },
            { name: "Folláin Nothing But Fruit Blackcurrant 340g" },
            { name: "Dunnes Stores Tomato Purée 140g" },
            { name: "Dunnes Stores Unsalted Rice Cakes 130g" },
            { name: "TREK White Choc & Raspberry Protein Flapjacks 3 x 50g" },
            { name: "TREK Biscoff Protein Flapjack 3 x 50g" },
            { name: "Kind Protein Dark Chocolate Nut Bars 3 x 42g (126g)" },
            { name: "Kind Protein Crunchy Peanut Butter 3 x 42g (126g)" },
            { name: "Dunnes Stores Wholefoods Bulgur Wheat 500g" },
            { name: "Dunnes Stores Wholefoods Butter Beans in Water 400g" },
            { name: "Dunnes Stores Wholefoods Red Kidney Beans in Water 400g" },
            { name: "Dunnes Stores Wholefoods Red Split Lentils 500g" },
            { name: "Epicure Organic Bijoux Verts Lentils in Water 400g" },
            { name: "Epicure Organic Black Beans in Water 400g" },
            { name: "Gem Bread Soda 500g" },
            { name: "Dunnes Stores Italian Tomato Passata 500g" },
            { name: "Dunnes Stores Spanish Extra Virgin Olive Oil 500ml" },
            { name: "Dunnes Stores Pure Vegetable Oil 1L", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-pure-vegetable-oil-1l-id-100806234" },
            { name: "Dunnes Stores Baking at Home Cocoa Powder 250g" },
            { name: "Dunnes Stores My Family Favourites Basmati Rice 1kg" },
            { name: "Dunnes Stores Organic Porridge Oats Wholegrain 1kg" },
            { name: "Dunnes Stores Irish Porridge Oats 1.5kg", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/256/product/dunnes-stores-irish-porridge-oats-15kg-id-100806224" },
            { name: "Dunnes Stores Organic Coconut Milk 400ml", icon: "🥥" },
            { name: "Dunnes Stores My Family Favourites Plain Flour 2kg" },
            { name: "Frontier Foods Tahini 270g" },
            { name: "Dunnes Stores Fusilli 500g", icon: "🍝", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-fusilli-500g-id-100883303" },
            { name: "Dunnes Stores Wholefoods Smooth Peanut Butter 340g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-wholefoods-smooth-peanut-butter-340g-id-100297805" },
        ],
    },
    {
        name: "Spices",
        items: [
            { name: "Dunnes Stores Bay Leaves 4g", icon: "🌿", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-bay-leaves-4g-id-100206145" },
        ],
    },
    {
        name: "Treats",
        items: [
            { name: "Reese's Milk Chocolate and Peanut Butter Cups, Multipack (5 Pack), 77g" },
            { name: "McVitie's Signature Chocolate Cream Swirls 142g" },
            { name: "Dunnes Stores Dark Chocolate Digestive Biscuits 300g" },
            { name: "Catch Funsize Bars 192g" },
        ],
    },
    {
        name: "Fresh Produce",
        items: [
            { name: "Dunnes Stores Organic Carrots 1kg" },
            { name: "Dunnes Stores 6 Fresh Bananas" },
            { name: "Dunnes Stores Peppery Wild Rocket Leaves 100g" },
            { name: "Dunnes Stores Organic Cucumber" },
            { name: "Dunnes Stores Grapefruit Loose 1'S" },
            { name: "Dunnes Stores Fresh Avocados 700g" },
            { name: "Dunnes Stores Supersweet Corn on the Cob 600g" },
            { name: "Donnelly Fresh Citrus Easy Peelers 1kg" },
            { name: "Dunnes Stores Fresh Root Ginger x 175g" },
            { name: "Dunnes Stores Italian Style Salad Mix 170g" },
            { name: "Dunnes Stores Green Kiwi 4pk" },
            { name: "Dunnes Stores Fresh Sweet Potatoes 750g" },
            { name: "Dunnes Stores Fresh Irish Parsnips", icon: "🥕" },
            { name: "Dunnes Stores Fresh Broccoli" },
            { name: "Dunnes Stores Cauliflower" },
            { name: "Dunnes Stores Loose Aubergine", icon: "🍆" },
            { name: "Dunnes Stores Loose Courgette" },
            { name: "Dunnes Stores Microwave Baby Potatoes 400g" },
            { name: "Rustic Irish Garlic", url: "https://www.dunnesstoresgrocery.com/sm/delivery/rsid/258/product/dunnes-stores-fresh-garlic-150g-id-100807374" },
            { name: "Dunnes Stores Red Pepper" },
            { name: "Dunnes Stores Organic Irish Potatoes 2kg" },
            { name: "Dunnes Stores Organic Celery", icon: "🥬" },
            { name: "Dunnes Stores Loose Celeriac", icon: "🧅", url: "https://www.dunnesstoresgrocery.com/product/dunnes-stores-loose-celeriac-id-100730080?srsltid=AfmBOorTNWkNF5jliIA2-LPHBNdWWIHiGgz7adIVf_BtQxCGv-IyU_PO" },
            { name: "Dunnes Stores My Family Favourites Red Onions" },
            { name: "Dunnes Stores My Family Favourites Onions 1kg", url: "https://www.dunnesstoresgrocery.com/product/dunnes-stores-my-family-favourites-onions-1kg-id-100290685" },
            { name: "Dunnes Stores Organic Vine Tomatoes 400g", icon: "🍅" },
            { name: "Dunnes Stores My Family Favourites Fresh Irish Leeks 500g", icon: "🥬" },
        ],
    },
    {
        name: "Meat & Alt",
        items: [
            { name: "Quorn Vegetarian Pieces 500g" },
            { name: "Sons of Butchers Cheatballs 200g" },
            { name: "Sons of Butchers Trick'n Strips 160g" },
            { name: "The Tofoo Co. Smoked Organic Tofu 225g" },
            { name: "Dunnes Stores Wafer Thin Chilli Glazed Irish Ham 10 Slices 130g" },
            { name: "Dunnes Stores Wafer Thin Smoked Bourbon Glazed Irish Ham 10 Slices 130g" },
            { name: "Quorn Vegan Chicken Free Slices 100g" },
            { name: "Quorn 12 Veggie Ham Slices 170g" },
            { name: "Quorn 12 Veggie Chicken Slices 170g" },
        ],
    },
    {
        name: "Freezer",
        items: [
            { name: "Dunnes Stores Freshly Frozen Petits Pois & Sweetcorn 750g", icon: "🌽" },
            { name: "Dunnes Stores Freshly Frozen Very Fine Green Beans 500g", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/256/product/dunnes-stores-freshly-frozen-very-fine-green-beans-500g-id-100202306", icon: "🫛" },
            { name: "Ardo Cultivated Blueberries 450g", icon: "🫐" },
            { name: "Ardo Raspberries 300g", icon: "🍓" },
        ],
    },
    {
        name: "Household",
        items: [
            { name: "Dunnes Stores Multi Purpose Kitchen Towel 3 Ply 4 Rolls", icon: "🧻" },
            { name: "Comfort Fabric Conditioner Pure 31 washes (930 ml)", icon: "🧴" },
            { name: "Dunnes Stores 12 Toilet Tissue Rolls", icon: "🧻", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-12-toilet-tissue-rolls-id-100326547" },
            { name: "Shannon Baking Parchment 12m", icon: "📜" },
            { name: "Crystale Platinum Dishwasher Tablets Lemon Fresh 26x18g (468g)" },
            { name: "Dunnes Stores Rinse Aid for Dishwasher 1 Litre", icon: "🧴" },
            { name: "Dishmatic 6 General Purpose Refills", icon: "🧽" },
            { name: "Dunnes Stores Classic Cat Food Chunks in Jelly Mixed Selection - Adult- 6 x 400g (2.4kg)" },
            { name: "Dunnes Stores My Family Favourites Cat Food Meaty Selection in Gravy 6x400g", icon: "🐈", url: "https://www.dunnesstoresgrocery.com/sm/delivery/rsid/253/product/dunnes-stores-my-family-favourites-cat-food-meaty-selection-in-gravy-6-x-400g-id-100821214?srsltid=AfmBOooxBab9q8x3rh6l7APFFv5R0MWS2jj_RyrFBY6LC3-Z8A15EvWG" },
            { name: "Kleenex Supporting Mind - Single Cube Tissue Box", icon: "🗳️" },
            { name: "Dunnes Stores Lemon Citrus Washing Up Liquid 500ml" },
            { name: "GreenAware 100% Compostable Food Waste Caddy Bin Liners 14 x 12L", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/256/product/greenaware-100-compostable-food-waste-caddy-bin-liners-14-x-12l-id-100859046", icon: "🗑️" },
            { name: "Dunnes Stores 30 Tie Handle Pedal Bin Liners 25L", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/256/product/dunnes-stores-30-tie-handle-pedal-bin-liners-25l-id-100866709", icon: "🗑️" },
        ],
    },
    {
        name: "Baby",
        items: [
            { name: "Dunnes Stores 36 Baby-Dry Easy on Easy off Pants 5 12-17kg" },
            { name: "Dunnes Stores 32 Baby-Dry Easy on Easy off Pants 6 15+kg", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-32-babydry-easy-on-easy-off-pants-6-15kg-id-100316733" },
            { name: "Glenilen Farm Kids Yoghurt Natural 90g" },
            { name: "Dunnes Stores Cleansing Cotton Pads" },
            { name: "Sudocrem Antiseptic Healing Cream 250g" },
            { name: "Beeline Kids Vitamin D3 Pump 28ml" },
        ],
    },
];
