window.products = [
    // Fridge
    { name: "Dunnes Stores Irish Whole Milk 1 Litre", category: "Fridge", "url": "https://www.dunnesstoresgrocery.com/product/dunnes-stores-irish-whole-milk-1-litre-id-100806906" },
    { name: "Łaciate 2,0% UHT Milk 1.5 Litre", category: "Fridge" },
    { name: "Dunnes Stores 12 Irish Free Range Eggs Medium", category: "Fridge" },
    { name: "Dunnes Stores 6 Irish Free Range Eggs Medium", category: "Fridge" },
    { name: "Dunnes Stores Organic Greek Style Natural Yogurt 500g", category: "Fridge" },
    { name: "Dunnes Stores Fresh Italian Ricotta 250g", category: "Fridge" },
    { name: "Mlekpol Semi-Fat Curd Cheese 275g", category: "Fridge" },
    { name: "Dunnes Stores My Family Favourites Irish Creamery Butter 454g", category: "Fridge" },
    { name: "Dunnes Stores My Family Favourites Irish Mild White Cheddar 500g", category: "Fridge" },
    { name: "Coburger Brie 200g", category: "Fridge" },
    { name: "Dunnes Stores Fresh Cream 250ml", category: "Fridge" },
    { name: "Dunnes Stores My Family Favourites Mozzarella 200g", category: "Fridge" },
    { name: "Dunnes Stores Mild & Firm Halloumi 250g", category: "Fridge", icon: "🧀" },
    { name: "Dunnes Stores Organic Irish Beef Round Steak Mince 355g", category: "Fridge", icon: "🥩" },
    { name: "Dunnes Stores Spanish Style Potato & Onion Tortilla 500g", category: "Fridge", icon: "🍳" },

    // Pantry
    { name: "Dunnes Stores Organic Spelt Sourdough 720g", category: "Pantry" },
    { name: "Dunnes Stores Organic Ancient Grains 4 Seed Sourdough 800g", category: "Pantry" },
    { name: "Dunnes Stores Organic Rye Sourdough 690g", category: "Pantry" },
    { name: "Dunnes Stores House Organic Seeded Sourdough 785g", category: "Pantry" },
    { name: "Dunnes Stores Italian Chopped Tomatoes in a Rich Tomato Juice 400g", category: "Pantry" },
    { name: "It'za 8 Plain Wraps 320g", category: "Pantry", icom: "🌮" },
    { name: "Dunnes Stores Wholefoods Chickpeas in Water 400g", category: "Pantry" },
    { name: "Dunnes Stores Wholefoods Cannellini Beans in Water 400g", category: "Pantry" },
    { name: "Folláin Nothing But Fruit Blackcurrant 340g", category: "Pantry" },
    { name: "Dunnes Stores Tomato Purée 140g", category: "Pantry" },
    { name: "Dunnes Stores Unsalted Rice Cakes 130g", category: "Pantry" },
    { name: "TREK White Choc & Raspberry Protein Flapjacks 3 x 50g", category: "Pantry" },
    { name: "TREK Biscoff Protein Flapjack 3 x 50g", category: "Pantry" },
    { name: "Kind Protein Dark Chocolate Nut Bars 3 x 42g (126g)", category: "Pantry" },
    { name: "Kind Protein Crunchy Peanut Butter 3 x 42g (126g)", category: "Pantry" },
    { name: "Dunnes Stores Wholefoods Bulgur Wheat 500g", category: "Pantry" },
    { name: "Dunnes Stores Wholefoods Butter Beans in Water 400g", category: "Pantry" },
    { name: "Dunnes Stores Wholefoods Red Kidney Beans in Water 400g", category: "Pantry" },
    { name: "Dunnes Stores Wholefoods Red Split Lentils 500g", category: "Pantry" },
    { name: "Epicure Organic Bijoux Verts Lentils in Water 400g", category: "Pantry" },
    { name: "Epicure Organic Black Beans in Water 400g", category: "Pantry" },
    { name: "Gem Bread Soda 500g", category: "Pantry" },
    { name: "Dunnes Stores Italian Tomato Passata 500g", category: "Pantry" },
    { name: "Dunnes Stores Spanish Extra Virgin Olive Oil 500ml", category: "Pantry" },
    { name: "Dunnes Stores Pure Vegetable Oil 1L\n", category: "Pantry", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-pure-vegetable-oil-1l-id-100806234" },
    { name: "Dunnes Stores Baking at Home Cocoa Powder 250g", category: "Pantry" },
    { name: "Dunnes Stores My Family Favourites Basmati Rice 1kg", category: "Pantry" },
    { name: "Dunnes Stores Organic Porridge Oats Wholegrain 1kg", category: "Pantry" },
    { name: "Dunnes Stores Organic Coconut Milk 400ml", category: "Pantry", icon: "🥥" },
    { name: "Dunnes Stores My Family Favourites Plain Flour 2kg", category: "Pantry" },
    { name: "Frontier Foods Tahini 270g", category: "Pantry" },
    { name: "Dunnes Stores Fusilli 500g", category: "Pantry", icon: "🍝", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-fusilli-500g-id-100883303" },

    // Spices
    { name: "Dunnes Stores Bay Leaves 4g", category: "Spices", icon: "🌿", url: "https://www.dunnesstoresgrocery.com/sm/pickup/rsid/253/product/dunnes-stores-bay-leaves-4g-id-100206145" },

    // Treats
    { name: "Reese's Milk Chocolate and Peanut Butter Cups, Multipack (5 Pack), 77g", category: "Treats" },
    { name: "McVitie's Signature Chocolate Cream Swirls 142g", category: "Treats" },
    { name: "Dunnes Stores Dark Chocolate Digestive Biscuits 300g", category: "Treats" },
    { name: "Catch Funsize Bars 192g", category: "Treats" },

    // Fresh Produce
    { name: "Dunnes Stores Organic Carrots 1kg", category: "Fresh Produce" },
    { name: "Dunnes Stores Handpicked Irish Baby Strawberries 125g", category: "Fresh Produce", icon: "🍓" },
    { name: "Dunnes Stores 6 Fresh Bananas", category: "Fresh Produce" },
    { name: "Dunnes Stores Peppery Wild Rocket Leaves 100g", category: "Fresh Produce" },
    { name: "Dunnes Stores Organic Cucumber", category: "Fresh Produce" },
    { name: "Dunnes Stores Grapefruit Loose 1'S", category: "Fresh Produce" },
    { name: "Dunnes Stores Fresh Avocados 700g", category: "Fresh Produce" },
    { name: "Dunnes Stores Supersweet Corn on the Cob 600g", category: "Fresh Produce" },
    { name: "Donnelly Fresh Citrus Easy Peelers 1kg", category: "Fresh Produce" },
    { name: "Dunnes Stores Fresh Root Ginger x 175g", category: "Fresh Produce", icon: "" },
    { name: "Dunnes Stores Italian Style Salad Mix 170g", category: "Fresh Produce" },
    { name: "Dunnes Stores Green Kiwi 4pk", category: "Fresh Produce" },
    { name: "Dunnes Stores Fresh Sweet Potatoes 750g", category: "Fresh Produce" },
    { name: "Dunnes Stores Fresh Irish Parsnips", category: "Fresh Produce", icon: "🥕" },
    { name: "Dunnes Stores Fresh Broccoli", category: "Fresh Produce" },
    { name: "Dunnes Stores Cauliflower", category: "Fresh Produce" },
    { name: "Dunnes Stores Loose Aubergine", category: "Fresh Produce", icon: "🍆" },
    { name: "Dunnes Stores Loose Courgette", category: "Fresh Produce" },
    { name: "Dunnes Stores Microwave Baby Potatoes 400g", category: "Fresh Produce" },
    { name: "Dunnes Stores Rustic Irish Garlic", category: "Fresh Produce" },
    { name: "Dunnes Stores Red Pepper", category: "Fresh Produce" },
    { name: "Dunnes Stores Organic Irish Potatoes 2kg", category: "Fresh Produce" },
    { name: "Dunnes Stores Organic Celery", category: "Fresh Produce", icon: "🥬" },
    { name: "Dunnes Stores My Family Favourites Red Onions", category: "Fresh Produce" },
    { name: "Dunnes Stores My Family Favourites Onions 1kg", category: "Fresh Produce", url: "dunnesstoresgrocery.com/product/dunnes-stores-my-family-favourites-onions-1kg-id-100290685" },
    { name: "Dunnes Stores Organic Vine Tomatoes 400g", category: "Fresh Produce", icon: "🍅" },
    { name: "Dunnes Stores My Family Favourites Fresh Irish Leeks 500g", category: "Fresh Produce", icon: "🥬" },

    // Meat & Veggie Alt
    { name: "Quorn Vegetarian Pieces 500g", category: "Meat & Alt" },
    { name: "Sons of Butchers Cheatballs 200g", category: "Meat & Alt" },
    { name: "Sons of Butchers Trick'n Strips 160g", category: "Meat & Alt" },
    { name: "The Tofoo Co. Smoked Organic Tofu 225g", category: "Meat & Alt" },
    { name: "Dunnes Stores Wafer Thin Chilli Glazed Irish Ham 10 Slices 130g", category: "Meat & Alt" },
    { name: "Dunnes Stores Wafer Thin Smoked Bourbon Glazed Irish Ham 10 Slices 130g", category: "Meat & Alt" },
    { name: "Quorn Vegan Chicken Free Slices 100g", category: "Meat & Alt" },
    { name: "Quorn 12 Veggie Ham Slices 170g", category: "Meat & Alt" },
    { name: "Quorn 12 Veggie Chicken Slices 170g", category: "Meat & Alt" },

    // Freezer
    { name: "Dunnes Stores Freshly Frozen Petits Pois & Sweetcorn 750g", category: "Freezer" },
    { name: "Dunnes Stores Freshly Frozen Very Fine Green Beans 500g", category: "Freezer" },
    { name: "Ardo Cultivated Blueberries 450g", category: "Freezer" },
    { name: "Ardo Raspberries 300g", category: "Freezer" },

    // Household & Pets
    { name: "Dunnes Stores Multi Purpose Kitchen Towel 3 Ply 4 Rolls", category: "Household" },
    { name: "Comfort Fabric Conditioner Pure 31 washes (930 ml)", category: "Household" },
    { name: "Dunnes Stores Toilet Tissue 12 Rolls", category: "Household" },
    { name: "Shannon Baking Parchment 12m", category: "Household" },
    { name: "Crystale Platinum Dishwasher Tablets Lemon Fresh 26x18g (468g)", category: "Household" },
    { name: "Dunnes Stores Rinse Aid for Dishwasher 1 Litre", category: "Household" },
    { name: "Dishmatic 6 General Purpose Refills", category: "Household" },
    { name: "Dunnes Stores Classic Cat Food Chunks in Jelly Mixed Selection - Adult- 6 x 400g (2.4kg)", category: "Household" },
    { name: "Dunnes Stores My Family Favourites Cat Food Meaty Selection in Gravy 6x400g", category: "Household" },
    { name: "Kleenex Supporting Mind - Single Cube Tissue Box", category: "Household" },

    // Baby
    { name: "Dunnes Stores 36 Baby-Dry Easy on Easy off Pants 5 12-17kg", category: "Baby" },
    { name: "Glenilen Farm Kids Yoghurt Natural 90g", category: "Baby" },
    { name: "Dunnes Stores Cleansing Cotton Pads", category: "Baby" },
    { name: "Sudocrem Antiseptic Healing Cream 250g", category: "Baby" },
    { name: "Beeline Kids Vitamin D3 Pump 28ml", category: "Baby" },
];
